<?php $this->load->view('website/recharge/navbar');?>

<div class="row">
  <div class="col-sm-12 homepage-form">
    <div class="panel mb20 panel-default panel-hovered">
      
       <div class="panel-body"> <?php echo form_open('recharge/proceed','id="recForm" method="post" autocomplete="off"')?>          <input type="hidden" name="redirect" value="Recharge/proceed"/>		   <input type="hidden" name="recharge_type"   value="Mobile postpaid" >          <div class="row">                                			<?php			if( $this->session->userdata('role_id') )			{			?>			<div class="col-md-3" style="float:right">                         <input type="checkbox" class="credit" name="mark_as_credit_user" value="1">              <label for="cabselect">Mark as credit</label>             </div>            <?php }			?>          </div>                    <div class="form-group">            <input type="text" class="form-control "  name="mobile_no" id="mobile_no" placeholder="Mobile no" maxlength="12" autofocus required>          </div>                              <div class="form-group">            <select class="form-control operators" name="operator" style="width: 100%" required>              <option value="" disabled="disabled">Select Operator</option>            </select>          </div>                    <div class="form-group">            <input type="text" class="form-control rcAmount" placeholder="Recharge Amount" name="rcAmount" id="rcAmount">          </div>		  		    <div class="form-group" id="acc_number" style="display:block"><input type="text" class="form-control rcAmount" name="postpaid_acc_no" value="" placeholder='Billing Number'>			</div>									           <div class="form-group homepage-rech ">                           <input type="text" name="mark_as_credit_comments" class="form-control Comments" style="display:none" placeholder="Enter Your Comments">            </div>          <div class="clearfix right">            <button class="btn btn-info mr5" type="submit" name="Proceed">Proceed</button>          </div>          </form>        </div>
    </div>
  </div>
</div>
<?php $this->load->view('website/recharge/right_block');?><script src="<?=base_url('web_assets/scripts/rechargeLandline.js')?>"></script><script>$('.checkpostpaidPrepaid').click(function(){	data = $(this).val();	if(data == "Mobile postpaid")	{		$("#acc_number").show();	}	else	{		$("#acc_number").hide();	}});$('.imgthumb').click(function(){  $('#mobile_large').attr('src',$(this).attr('src'));});$('.credit').click(function(){  if ($(this).is(':checked')){  $(".Comments").show()  } else {    $(".Comments").hide()  };    });$(document).ready(function(){    $("#recForm").validate({                    rules: {                            mobile_no:{required:true,minlength:10,maxlength:12},                             operator:{required:true},                             rcAmount:{required:true, number: true},							 				                            },                    messages: {                            mobile_no:{required:"Please enter mobile no"},                            operator:{required: "Please select operator"},                            rcAmount:{required: "Please enter recharge amount",number:"Amount should be in numeric"},							                            },                                            submitHandler: function(form) {                    form.submit();                }                                                            });										});</script>