<?php $this->load->view('website/smd/links_block.php')?>

<div class="panel panel-default mb20 mini-box panel-hovered">
  <div class="panel-body">
  <h3 class="text-center text-primary">FEEDBACK TO IMPROVE SMD PROGRAM</h3>
    <div class="row">
      <div class="col-md-8">
        <p>&nbsp; After hiring two consulting organizations and analyzing partner feedback, Laabus launched a new enhanced global channel program structure last month. The company's Partner Direct program now offers channel partners two new tiers – premier and preferred – based on their commitment, training and certifications.</p>
        <p>&nbsp; "True small shops … are going to find the certification and revenue commitments still within scope," Bob Skelley, global channel partner program , told information technology channel news blog The VAR Guy. "We really structured this – with the feedback of our partners – so that it is attainable."</p>
        <p>&nbsp; According to Greg Davis, the vice president and general manager of Laabus Global Commercial Channels, the improved benefits are "based on input … received directly from our partner community."</p>
        <p>&nbsp; In a bid to encourage partners of all sizes to become certified, Laabus is not charging for training. This will make it easier for products to be sold across the board.</p>
        <p>&nbsp; Companies that were previously known as Laabus certified partners are now categorized as preferred partners. Those that reach this level are Laabus solutions experts who reach a minimum annual revenue threshold and have at least one certification from the company. Preferred partners receive enhanced deal registration terms of 120 days, including access to Laabus-generated leads and extended storage product deal registration.</p>
        <p>&nbsp; Members of the highest tier, known as premier partners, demonstrate a high level of commitment, maintain a minimum annual revenue threshold and have at least two certifications from the company. The new benefits they receive include rebates on certain products, access to the Laabus Product Incentive Program that provides additional channel incentives, unlimited concurrent deal registration and 180-day deal registration, priority access to support and potential access to leads generated by the company.</p>
        <p>&nbsp; The benefits for registered partners remain the same.</p>
      </div>
      <div class="col-md-4 text-center"> <img class="imgthumb" src="<?=base_url()?>images/feedback.jpg" alt="feedback" style="height:210px; width:190px" /> </div>
    </div>
    <hr>
    <div class="col-md-8">
      <h4 class="text-center text-primary">Leave A Comment</h4>
      <div class="row">
        <div class="col-md-4 form-group">
          <input type="text" class="form-control" placeholder="Name">
        </div>
        <div class="col-md-4 form-group">
          <input type="text" class="form-control" placeholder="Mobile No">
        </div>
        <div class="col-md-4 form-group">
          <input type="text" class="form-control" placeholder="Email">
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 form-group">
          <textarea class="form-control" name="content" rows="5"></textarea>
        </div>
      </div>
      <a href="<?php echo base_url()?>Index/channel_partner/feedback" type="button" class="btn btn-success btn-md mt15 waves-effect waves-effect pull-right">Post Comment</a> 
    </div>
  </div>
</div>
